CREATE TABLE IF NOT EXISTS contracts (
  id TEXT PRIMARY KEY,
  title TEXT,
  type TEXT,
  agency TEXT,
  sub_agency TEXT,
  contracting_office TEXT,
  value TEXT,
  award_amt BIGINT,
  naics TEXT,
  set_aside TEXT,
  sol_num TEXT,
  posted_date TEXT,
  deadline TEXT,
  recipient TEXT,
  poc TEXT,
  poc_email TEXT,
  alt_poc TEXT,
  alt_poc_email TEXT,
  description TEXT,
  rationale TEXT,
  urgency TEXT,
  urgency_note TEXT,
  sam_url TEXT,
  loc TEXT,
  extra TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);
